# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ping <- function() {
    .Call(`_gromtools_ping`)
}

grex_axpy_all_snps_to_dense <- function(indptr, indices, data, pgen_file, raw_sample_ct, snp_chunk, sample_subset, meanimpute, h5_path, CHUNK, gene_pos, exportChunk, n_total_genes, create_new, G_in = NULL, showWarnings = FALSE) {
    .Call(`_gromtools_grex_axpy_all_snps_to_dense`, indptr, indices, data, pgen_file, raw_sample_ct, snp_chunk, sample_subset, meanimpute, h5_path, CHUNK, gene_pos, exportChunk, n_total_genes, create_new, G_in, showWarnings)
}

grex_omp_info <- function() {
    .Call(`_gromtools_grex_omp_info`)
}

rcpp_hello_world <- function() {
    .Call(`_gromtools_rcpp_hello_world`)
}

