// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ping
int ping();
RcppExport SEXP _gromtools_ping() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ping());
    return rcpp_result_gen;
END_RCPP
}
// grom_axpy_engine
Rcpp::NumericMatrix grom_axpy_engine(Rcpp::IntegerVector indptr, Rcpp::IntegerVector indices, Rcpp::NumericVector data, const std::string& pgen_file, int raw_sample_ct, size_t snp_chunk, Rcpp::IntegerVector sample_subset, bool meanimpute, const std::string& grom_file, size_t CHUNK, Rcpp::IntegerVector gene_pos, size_t exportChunk, size_t n_total_genes, bool create_new, Rcpp::Nullable<Rcpp::NumericMatrix> G_in, bool showWarnings, bool rounded_mean, int threads, int pgen_threads, int write_threads);
RcppExport SEXP _gromtools_grom_axpy_engine(SEXP indptrSEXP, SEXP indicesSEXP, SEXP dataSEXP, SEXP pgen_fileSEXP, SEXP raw_sample_ctSEXP, SEXP snp_chunkSEXP, SEXP sample_subsetSEXP, SEXP meanimputeSEXP, SEXP grom_fileSEXP, SEXP CHUNKSEXP, SEXP gene_posSEXP, SEXP exportChunkSEXP, SEXP n_total_genesSEXP, SEXP create_newSEXP, SEXP G_inSEXP, SEXP showWarningsSEXP, SEXP rounded_meanSEXP, SEXP threadsSEXP, SEXP pgen_threadsSEXP, SEXP write_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type indptr(indptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type pgen_file(pgen_fileSEXP);
    Rcpp::traits::input_parameter< int >::type raw_sample_ct(raw_sample_ctSEXP);
    Rcpp::traits::input_parameter< size_t >::type snp_chunk(snp_chunkSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sample_subset(sample_subsetSEXP);
    Rcpp::traits::input_parameter< bool >::type meanimpute(meanimputeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type grom_file(grom_fileSEXP);
    Rcpp::traits::input_parameter< size_t >::type CHUNK(CHUNKSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type gene_pos(gene_posSEXP);
    Rcpp::traits::input_parameter< size_t >::type exportChunk(exportChunkSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_total_genes(n_total_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type create_new(create_newSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type G_in(G_inSEXP);
    Rcpp::traits::input_parameter< bool >::type showWarnings(showWarningsSEXP);
    Rcpp::traits::input_parameter< bool >::type rounded_mean(rounded_meanSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< int >::type pgen_threads(pgen_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type write_threads(write_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(grom_axpy_engine(indptr, indices, data, pgen_file, raw_sample_ct, snp_chunk, sample_subset, meanimpute, grom_file, CHUNK, gene_pos, exportChunk, n_total_genes, create_new, G_in, showWarnings, rounded_mean, threads, pgen_threads, write_threads));
    return rcpp_result_gen;
END_RCPP
}
// grom_decode_pgen_range
Rcpp::NumericMatrix grom_decode_pgen_range(const std::string& pgen_file, int raw_sample_ct, size_t first_variant_1based, size_t variant_count, Rcpp::IntegerVector sample_subset, bool meanimpute, bool rounded_mean, int pgen_threads);
RcppExport SEXP _gromtools_grom_decode_pgen_range(SEXP pgen_fileSEXP, SEXP raw_sample_ctSEXP, SEXP first_variant_1basedSEXP, SEXP variant_countSEXP, SEXP sample_subsetSEXP, SEXP meanimputeSEXP, SEXP rounded_meanSEXP, SEXP pgen_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pgen_file(pgen_fileSEXP);
    Rcpp::traits::input_parameter< int >::type raw_sample_ct(raw_sample_ctSEXP);
    Rcpp::traits::input_parameter< size_t >::type first_variant_1based(first_variant_1basedSEXP);
    Rcpp::traits::input_parameter< size_t >::type variant_count(variant_countSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sample_subset(sample_subsetSEXP);
    Rcpp::traits::input_parameter< bool >::type meanimpute(meanimputeSEXP);
    Rcpp::traits::input_parameter< bool >::type rounded_mean(rounded_meanSEXP);
    Rcpp::traits::input_parameter< int >::type pgen_threads(pgen_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(grom_decode_pgen_range(pgen_file, raw_sample_ct, first_variant_1based, variant_count, sample_subset, meanimpute, rounded_mean, pgen_threads));
    return rcpp_result_gen;
END_RCPP
}
// grom_decode_pgen_range_readlist
Rcpp::NumericMatrix grom_decode_pgen_range_readlist(const std::string& pgen_file, int raw_sample_ct, size_t first_variant_1based, size_t variant_count, Rcpp::IntegerVector sample_subset, bool meanimpute, bool rounded_mean);
RcppExport SEXP _gromtools_grom_decode_pgen_range_readlist(SEXP pgen_fileSEXP, SEXP raw_sample_ctSEXP, SEXP first_variant_1basedSEXP, SEXP variant_countSEXP, SEXP sample_subsetSEXP, SEXP meanimputeSEXP, SEXP rounded_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pgen_file(pgen_fileSEXP);
    Rcpp::traits::input_parameter< int >::type raw_sample_ct(raw_sample_ctSEXP);
    Rcpp::traits::input_parameter< size_t >::type first_variant_1based(first_variant_1basedSEXP);
    Rcpp::traits::input_parameter< size_t >::type variant_count(variant_countSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sample_subset(sample_subsetSEXP);
    Rcpp::traits::input_parameter< bool >::type meanimpute(meanimputeSEXP);
    Rcpp::traits::input_parameter< bool >::type rounded_mean(rounded_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(grom_decode_pgen_range_readlist(pgen_file, raw_sample_ct, first_variant_1based, variant_count, sample_subset, meanimpute, rounded_mean));
    return rcpp_result_gen;
END_RCPP
}
// grom_test_readlist_buffer_contract
Rcpp::List grom_test_readlist_buffer_contract(const std::string& pgen_file, int raw_sample_ct, size_t first_variant_1based, size_t variant_count, Rcpp::IntegerVector sample_subset, bool meanimpute, bool rounded_mean);
RcppExport SEXP _gromtools_grom_test_readlist_buffer_contract(SEXP pgen_fileSEXP, SEXP raw_sample_ctSEXP, SEXP first_variant_1basedSEXP, SEXP variant_countSEXP, SEXP sample_subsetSEXP, SEXP meanimputeSEXP, SEXP rounded_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pgen_file(pgen_fileSEXP);
    Rcpp::traits::input_parameter< int >::type raw_sample_ct(raw_sample_ctSEXP);
    Rcpp::traits::input_parameter< size_t >::type first_variant_1based(first_variant_1basedSEXP);
    Rcpp::traits::input_parameter< size_t >::type variant_count(variant_countSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sample_subset(sample_subsetSEXP);
    Rcpp::traits::input_parameter< bool >::type meanimpute(meanimputeSEXP);
    Rcpp::traits::input_parameter< bool >::type rounded_mean(rounded_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(grom_test_readlist_buffer_contract(pgen_file, raw_sample_ct, first_variant_1based, variant_count, sample_subset, meanimpute, rounded_mean));
    return rcpp_result_gen;
END_RCPP
}
// grom_test_pgen_workspace_estimate
Rcpp::List grom_test_pgen_workspace_estimate(const std::string& pgen_file, int raw_sample_ct, Rcpp::IntegerVector sample_subset, size_t variant_1based, bool rounded_mean);
RcppExport SEXP _gromtools_grom_test_pgen_workspace_estimate(SEXP pgen_fileSEXP, SEXP raw_sample_ctSEXP, SEXP sample_subsetSEXP, SEXP variant_1basedSEXP, SEXP rounded_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pgen_file(pgen_fileSEXP);
    Rcpp::traits::input_parameter< int >::type raw_sample_ct(raw_sample_ctSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sample_subset(sample_subsetSEXP);
    Rcpp::traits::input_parameter< size_t >::type variant_1based(variant_1basedSEXP);
    Rcpp::traits::input_parameter< bool >::type rounded_mean(rounded_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(grom_test_pgen_workspace_estimate(pgen_file, raw_sample_ct, sample_subset, variant_1based, rounded_mean));
    return rcpp_result_gen;
END_RCPP
}
// grex_omp_info
Rcpp::IntegerVector grex_omp_info();
RcppExport SEXP _gromtools_grex_omp_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(grex_omp_info());
    return rcpp_result_gen;
END_RCPP
}
// sqlite_read_model_db_cpp
Rcpp::List sqlite_read_model_db_cpp(const std::string& db_path, Rcpp::Nullable<Rcpp::CharacterVector> extra_cols);
RcppExport SEXP _gromtools_sqlite_read_model_db_cpp(SEXP db_pathSEXP, SEXP extra_colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type db_path(db_pathSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type extra_cols(extra_colsSEXP);
    rcpp_result_gen = Rcpp::wrap(sqlite_read_model_db_cpp(db_path, extra_cols));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gromtools_ping", (DL_FUNC) &_gromtools_ping, 0},
    {"_gromtools_grom_axpy_engine", (DL_FUNC) &_gromtools_grom_axpy_engine, 20},
    {"_gromtools_grom_decode_pgen_range", (DL_FUNC) &_gromtools_grom_decode_pgen_range, 8},
    {"_gromtools_grom_decode_pgen_range_readlist", (DL_FUNC) &_gromtools_grom_decode_pgen_range_readlist, 7},
    {"_gromtools_grom_test_readlist_buffer_contract", (DL_FUNC) &_gromtools_grom_test_readlist_buffer_contract, 7},
    {"_gromtools_grom_test_pgen_workspace_estimate", (DL_FUNC) &_gromtools_grom_test_pgen_workspace_estimate, 5},
    {"_gromtools_grex_omp_info", (DL_FUNC) &_gromtools_grex_omp_info, 0},
    {"_gromtools_sqlite_read_model_db_cpp", (DL_FUNC) &_gromtools_sqlite_read_model_db_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_gromtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
