// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ping
int ping();
RcppExport SEXP _gromtools_ping() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ping());
    return rcpp_result_gen;
END_RCPP
}
// grom_axpy_engine
Rcpp::NumericMatrix grom_axpy_engine(Rcpp::IntegerVector indptr, Rcpp::IntegerVector indices, Rcpp::NumericVector data, const std::string& pgen_file, int raw_sample_ct, size_t snp_chunk, Rcpp::IntegerVector sample_subset, bool meanimpute, const std::string& grom_file, size_t CHUNK, Rcpp::IntegerVector gene_pos, size_t exportChunk, size_t n_total_genes, bool create_new, Rcpp::Nullable<Rcpp::NumericMatrix> G_in, bool showWarnings, bool rounded_mean);
RcppExport SEXP _gromtools_grom_axpy_engine(SEXP indptrSEXP, SEXP indicesSEXP, SEXP dataSEXP, SEXP pgen_fileSEXP, SEXP raw_sample_ctSEXP, SEXP snp_chunkSEXP, SEXP sample_subsetSEXP, SEXP meanimputeSEXP, SEXP grom_fileSEXP, SEXP CHUNKSEXP, SEXP gene_posSEXP, SEXP exportChunkSEXP, SEXP n_total_genesSEXP, SEXP create_newSEXP, SEXP G_inSEXP, SEXP showWarningsSEXP, SEXP rounded_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type indptr(indptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type pgen_file(pgen_fileSEXP);
    Rcpp::traits::input_parameter< int >::type raw_sample_ct(raw_sample_ctSEXP);
    Rcpp::traits::input_parameter< size_t >::type snp_chunk(snp_chunkSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sample_subset(sample_subsetSEXP);
    Rcpp::traits::input_parameter< bool >::type meanimpute(meanimputeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type grom_file(grom_fileSEXP);
    Rcpp::traits::input_parameter< size_t >::type CHUNK(CHUNKSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type gene_pos(gene_posSEXP);
    Rcpp::traits::input_parameter< size_t >::type exportChunk(exportChunkSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_total_genes(n_total_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type create_new(create_newSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type G_in(G_inSEXP);
    Rcpp::traits::input_parameter< bool >::type showWarnings(showWarningsSEXP);
    Rcpp::traits::input_parameter< bool >::type rounded_mean(rounded_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(grom_axpy_engine(indptr, indices, data, pgen_file, raw_sample_ct, snp_chunk, sample_subset, meanimpute, grom_file, CHUNK, gene_pos, exportChunk, n_total_genes, create_new, G_in, showWarnings, rounded_mean));
    return rcpp_result_gen;
END_RCPP
}
// grex_omp_info
Rcpp::IntegerVector grex_omp_info();
RcppExport SEXP _gromtools_grex_omp_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(grex_omp_info());
    return rcpp_result_gen;
END_RCPP
}
// NewPvar
SEXP NewPvar(String filename, bool omit_chrom, bool omit_pos);
RcppExport SEXP _gromtools_NewPvar(SEXP filenameSEXP, SEXP omit_chromSEXP, SEXP omit_posSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< bool >::type omit_chrom(omit_chromSEXP);
    Rcpp::traits::input_parameter< bool >::type omit_pos(omit_posSEXP);
    rcpp_result_gen = Rcpp::wrap(NewPvar(filename, omit_chrom, omit_pos));
    return rcpp_result_gen;
END_RCPP
}
// GetVariantChrom
String GetVariantChrom(List pvar, int variant_num);
RcppExport SEXP _gromtools_GetVariantChrom(SEXP pvarSEXP, SEXP variant_numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pvar(pvarSEXP);
    Rcpp::traits::input_parameter< int >::type variant_num(variant_numSEXP);
    rcpp_result_gen = Rcpp::wrap(GetVariantChrom(pvar, variant_num));
    return rcpp_result_gen;
END_RCPP
}
// GetVariantPos
int GetVariantPos(List pvar, int variant_num);
RcppExport SEXP _gromtools_GetVariantPos(SEXP pvarSEXP, SEXP variant_numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pvar(pvarSEXP);
    Rcpp::traits::input_parameter< int >::type variant_num(variant_numSEXP);
    rcpp_result_gen = Rcpp::wrap(GetVariantPos(pvar, variant_num));
    return rcpp_result_gen;
END_RCPP
}
// GetVariantId
String GetVariantId(List pvar, int variant_num);
RcppExport SEXP _gromtools_GetVariantId(SEXP pvarSEXP, SEXP variant_numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pvar(pvarSEXP);
    Rcpp::traits::input_parameter< int >::type variant_num(variant_numSEXP);
    rcpp_result_gen = Rcpp::wrap(GetVariantId(pvar, variant_num));
    return rcpp_result_gen;
END_RCPP
}
// GetVariantsById
IntegerVector GetVariantsById(List pvar, String id);
RcppExport SEXP _gromtools_GetVariantsById(SEXP pvarSEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pvar(pvarSEXP);
    Rcpp::traits::input_parameter< String >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(GetVariantsById(pvar, id));
    return rcpp_result_gen;
END_RCPP
}
// GetAlleleCode
String GetAlleleCode(List pvar, int variant_num, int allele_num);
RcppExport SEXP _gromtools_GetAlleleCode(SEXP pvarSEXP, SEXP variant_numSEXP, SEXP allele_numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pvar(pvarSEXP);
    Rcpp::traits::input_parameter< int >::type variant_num(variant_numSEXP);
    Rcpp::traits::input_parameter< int >::type allele_num(allele_numSEXP);
    rcpp_result_gen = Rcpp::wrap(GetAlleleCode(pvar, variant_num, allele_num));
    return rcpp_result_gen;
END_RCPP
}
// ClosePvar
void ClosePvar(List pvar);
RcppExport SEXP _gromtools_ClosePvar(SEXP pvarSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pvar(pvarSEXP);
    ClosePvar(pvar);
    return R_NilValue;
END_RCPP
}
// sqlite_read_model_db_cpp
Rcpp::List sqlite_read_model_db_cpp(const std::string& db_path, Rcpp::Nullable<Rcpp::CharacterVector> extra_cols);
RcppExport SEXP _gromtools_sqlite_read_model_db_cpp(SEXP db_pathSEXP, SEXP extra_colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type db_path(db_pathSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type extra_cols(extra_colsSEXP);
    rcpp_result_gen = Rcpp::wrap(sqlite_read_model_db_cpp(db_path, extra_cols));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gromtools_ping", (DL_FUNC) &_gromtools_ping, 0},
    {"_gromtools_grom_axpy_engine", (DL_FUNC) &_gromtools_grom_axpy_engine, 17},
    {"_gromtools_grex_omp_info", (DL_FUNC) &_gromtools_grex_omp_info, 0},
    {"_gromtools_NewPvar", (DL_FUNC) &_gromtools_NewPvar, 3},
    {"_gromtools_GetVariantChrom", (DL_FUNC) &_gromtools_GetVariantChrom, 2},
    {"_gromtools_GetVariantPos", (DL_FUNC) &_gromtools_GetVariantPos, 2},
    {"_gromtools_GetVariantId", (DL_FUNC) &_gromtools_GetVariantId, 2},
    {"_gromtools_GetVariantsById", (DL_FUNC) &_gromtools_GetVariantsById, 2},
    {"_gromtools_GetAlleleCode", (DL_FUNC) &_gromtools_GetAlleleCode, 3},
    {"_gromtools_ClosePvar", (DL_FUNC) &_gromtools_ClosePvar, 1},
    {"_gromtools_sqlite_read_model_db_cpp", (DL_FUNC) &_gromtools_sqlite_read_model_db_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_gromtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
