# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ping <- function() {
    .Call(`_gromtools_ping`)
}

grom_axpy_engine <- function(indptr, indices, data, pgen_file, raw_sample_ct, snp_chunk, sample_subset, meanimpute, grom_file, CHUNK, gene_pos, exportChunk, n_total_genes, create_new, G_in = NULL, showWarnings = FALSE, rounded_mean = FALSE) {
    .Call(`_gromtools_grom_axpy_engine`, indptr, indices, data, pgen_file, raw_sample_ct, snp_chunk, sample_subset, meanimpute, grom_file, CHUNK, gene_pos, exportChunk, n_total_genes, create_new, G_in, showWarnings, rounded_mean)
}

grex_omp_info <- function() {
    .Call(`_gromtools_grex_omp_info`)
}

