# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ping <- function() {
    .Call(`_gromtools_ping`)
}

grom_axpy_engine <- function(indptr, indices, data, pgen_file, raw_sample_ct, snp_chunk, sample_subset, meanimpute, grom_file, CHUNK, gene_pos, exportChunk, n_total_genes, create_new, G_in = NULL, showWarnings = FALSE, rounded_mean = FALSE) {
    .Call(`_gromtools_grom_axpy_engine`, indptr, indices, data, pgen_file, raw_sample_ct, snp_chunk, sample_subset, meanimpute, grom_file, CHUNK, gene_pos, exportChunk, n_total_genes, create_new, G_in, showWarnings, rounded_mean)
}

grex_omp_info <- function() {
    .Call(`_gromtools_grex_omp_info`)
}

#' Loads variant positions, IDs, and allele codes from a .pvar or .bim file
#' (which can be compressed with gzip or Zstd).
#'
#' @param filename .pvar/.bim file path.
#' @param omit_chrom Whether to skip CHROM column.
#' @param omit_pos Whether to skip POS column.
#' @return A pvar object, which can be queried for variant IDs and allele
#' codes.
#' @export
NewPvar <- function(filename, omit_chrom = FALSE, omit_pos = FALSE) {
    .Call(`_gromtools_NewPvar`, filename, omit_chrom, omit_pos)
}

#' Retrieve chromosome ID for given variant index.
#'
#' @param pvar Object returned by NewPvar().
#' @param variant_num Variant index (1-based).
#' @return Chromosome ID for the variant_numth variant.
#' @export
GetVariantChrom <- function(pvar, variant_num) {
    .Call(`_gromtools_GetVariantChrom`, pvar, variant_num)
}

#' Retrieve POS (base-pair coordinate on a chromosome) for given variant
#' index.
#'
#' @param pvar Object returned by NewPvar().
#' @param variant_num Variant index (1-based).
#' @return POS for the variant_numth variant.
#' @export
GetVariantPos <- function(pvar, variant_num) {
    .Call(`_gromtools_GetVariantPos`, pvar, variant_num)
}

#' Convert variant index to variant ID string.
#'
#' @param pvar Object returned by NewPvar().
#' @param variant_num Variant index (1-based).
#' @return The variant_numth variant ID string.
#' @export
GetVariantId <- function(pvar, variant_num) {
    .Call(`_gromtools_GetVariantId`, pvar, variant_num)
}

#' Convert variant ID string to variant index(es).
#'
#' @param pvar Object returned by NewPvar().
#' @param id Variant ID to look up.
#' @return A list of all (1-based) variant indices with the given variant ID.
#' @export
GetVariantsById <- function(pvar, id) {
    .Call(`_gromtools_GetVariantsById`, pvar, id)
}

#' Look up an allele code.
#'
#' @param pvar Object returned by NewPvar().
#' @param variant_num Variant index (1-based).
#' @param allele_num Allele index (1-based).
#' @return The allele_numth allele code for the variant_numth variant.
#' allele_num=1 corresponds to the REF allele, allele_num=2 corresponds to the
#' first ALT allele, allele_num=3 corresponds to the second ALT allele if it
#' exists and errors out otherwise, etc.
#' @export
GetAlleleCode <- function(pvar, variant_num, allele_num) {
    .Call(`_gromtools_GetAlleleCode`, pvar, variant_num, allele_num)
}

#' Closes a pvar object, releasing memory.
#'
#' @param pvar Object returned by NewPvar().
#' @return No return value, called for side-effect.
#' @export
ClosePvar <- function(pvar) {
    invisible(.Call(`_gromtools_ClosePvar`, pvar))
}

